### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by fdkssdks** [reconstruct-on-the-fly/pycalibrate#1]

**Comment by fdkssdks** [comment]
I use this command but it keep saying 0 images found
python calibrate.py images/ --pattern 4X4
```
Found 0 images
Finding points Traceback (most recent call last):
  File "calibrate.py", line 100, in <module>
    out = calibrate(images)
  File "calibrate.py", line 59, in calibrate
    obj_points, img_points = find_points(images)
  File "calibrate.py", line 33, in find_points
    for (image, color_image) in images:
TypeError: 'NoneType' object is not iterable
```
